name: check

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm tsc
      - run: pnpm lint:ci
      - run: pnpm stylelint:ci
      - run: pnpm format:ci
      - run: pnpm test
      - run: pnpm build
